### ISSUE TITLE
Heap Sort in GoLang

### ISSUE THREAD

**Issue by mayankagwl** [nikochiko/cool-algos#35] opened 2020-10-01 09:55 UTC
Implement the Heap Sort Algorithm in GoLang

**Comment by mayankagwl** [comment] 2020-10-01 09:56
@nikochiko please assign it to me

**Comment by nikochiko** [comment] 2020-10-01 10:22
Hey, you're already assigned to #34 . Can you finish that first? 
Till then the issue is open for all

**Comment by mayankagwl** [comment] 2020-10-01 11:11
@nikochiko Can I work on this now

**Comment by nikochiko** [comment] 2020-10-01 11:13
Sure! Assigned

**Comment by mayankagwl** [comment] 2020-10-02 00:35
@nikochiko Raised PR https://github.com/nikochiko/cool-algos/pull/58

**Closed as completed** 2020-10-04 11:48 UTC
